config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'lists', to: 'lists#index'
  get 'lists/new'
  get 'lists/create'
  get 'lists/add_plant'
  get 'lists/remove_plant'
  get 'lists/delete'
  get 'lists/show'
  get 'users/index'
  get 'users/new'
  get 'users/create'

  resources :plants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user_id
  belongs_to :plant_id
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def add_plant
  end

  def remove_plant
  end

  def delete
  end

  def show
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plantlist = Plant.order(:common_name).all
  end

  def new
    @plant = Plant.new
  end

  def create
    Plant.create(plant_params)
    redirect_to plants_path
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def edit
  end

  private
  def plant_params
    params.require(:plant).permit(:common_name, :sc_name, :img_url, :info)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Plant Database', plants_path %></li>
          <li><%= link_to 'View Lists', lists_path %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/lists/add_plant.html.erb
<h1>Lists#add_plant</h1>
<p>Find me in app/views/lists/add_plant.html.erb</p>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/delete.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/lists/delete.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/remove_plant.html.erb
<h1>Lists#remove_plant</h1>
<p>Find me in app/views/lists/remove_plant.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/edit.html.erb
<h1>Plants#edit</h1>
<p>Find me in app/views/plants/edit.html.erb</p>

app/views/plants/index.html.erb
<h1>Plant Database</h1>
<%= link_to 'Add Plant to the Database', new_plant_path %>
    <% @plantlist.each do |data| %>
    <div class= "plant" >
        <img src="<%= data.img_url %>" width="150" height="150">
        <div class= "titles">
            <h3><%= data.common_name %></h3>
            <h5><i><%= data.sc_name %></i></h5>
            <%= link_to 'Show Info', plant_path(data.id) %>
        </div>
    </div>
    <% end %>

app/views/plants/new.html.erb
<h1>Plants#new</h1>
<p>Find me in app/views/plants/new.html.erb</p>

<%= form_with model: @plant, local: true do |f| %>
    <%= f.label :common_name, :'Plant Name:' %> <%= f.text_field :common_name %><br>
    <%= f.label :sc_name, :'Scientific Name:' %> <%= f.text_field :sc_name %><br>
    <%= f.label :img_url, :'Image URL:' %> <%= f.text_field :img_url %><br>
    <%= f.label :info, :'Information:' %> <%= f.text_area :info %><br>
    <%= f.submit %>
<% end %>

app/views/plants/show.html.erb
<p><%= link_to 'Back to Plant Database', plants_path %></p>
<h1><%= @plant.common_name %></h1>
<h3><i><%= @plant.sc_name %></i></h3>
<img src="<%= @plant.img_url %>" width="300" height="300">
<p><%= @plant.info %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to The Plantabase!</h1>